//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2014.3.1721.45")]
[assembly: AssemblyFileVersion("2014.3.1721.45")]
[assembly: AssemblyCopyright("Copyright © 2014-2014 Telerik AD")]
[assembly: AssemblyCompany("Telerik AD")]


